name: publish

on:
  release:
    types:
      - published

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Authenticate with Quay.io
        uses: docker/login-action@v3.0.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Generate image tag
        id: image_tag
        run: |
          echo tag=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//') >> $GITHUB_OUTPUT

      - name: Build image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            quay.io/tadas/rally-exporter:latest
            quay.io/tadas/rally-exporter:${{ steps.image_tag.outputs.tag }}
